### ISSUE TITLE
issue in ubuntu 18.04

### ISSUE THREAD

**Issue by ankit20893** [mern-stack/mern#6]
![Screenshot from 2019-04-03 16-30-54](https://user-images.githubusercontent.com/12858398/55474100-faa2c880-562d-11e9-8ed3-491b64f16225.png)

**Comment by riteshsingh1** [comment]
install redux devtools or comment `  window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()` in `store.js`
